"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.NameInstance = exports.Name = void 0;
const web3_1 = require("@alephium/web3");
const Name_ral_json_1 = __importDefault(require("../forward_name_resolver/Name.ral.json"));
const contracts_1 = require("./contracts");
const types_1 = require("./types");
class Factory extends web3_1.ContractFactory {
    constructor() {
        super(...arguments);
        this.eventIndex = { MetadataUpdated: 0 };
        this.consts = {
            ErrorCodes: {
                OnlyParentAllowed: BigInt("0"),
                NFTNotFound: BigInt("1"),
                NFTNotPartOfCollection: BigInt("2"),
                OnlyNftOwnerAllowed: BigInt("3"),
                NameHasNotExpired: BigInt("4"),
                CannotRenewName: BigInt("5"),
                TokenAlreadyGenerated: BigInt("6"),
                ReverseAddressNotFound: BigInt("7"),
                OnlyNftOwnerOrHolderAllowed: BigInt("8"),
                IncorrectFarmInputAmount: BigInt("9"),
                CropHasNotExpired: BigInt("10"),
                FarmInputAmountNotConsumed: BigInt("11"),
                FarmAlreadyGenerated: BigInt("12"),
            },
            Keys: { Names: "01", Token: "02", Farm: "03" },
        };
        this.tests = {
            getTokenUri: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getTokenUri", params, contracts_1.getContractByCodeHash);
            }),
            getCollectionIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getCollectionIndex", params, contracts_1.getContractByCodeHash);
            }),
            getName: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getName", params, contracts_1.getContractByCodeHash);
            }),
            getDescription: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getDescription", params, contracts_1.getContractByCodeHash);
            }),
            getImage: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getImage", params, contracts_1.getContractByCodeHash);
            }),
            getTraitCount: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getTraitCount", params, contracts_1.getContractByCodeHash);
            }),
            getTraitAtIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getTraitAtIndex", params, contracts_1.getContractByCodeHash);
            }),
            getNFTIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getNFTIndex", params, contracts_1.getContractByCodeHash);
            }),
            getCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getCapitalisation", params, contracts_1.getContractByCodeHash);
            }),
            getExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getExpires", params, contracts_1.getContractByCodeHash);
            }),
            getAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getAddress", params, contracts_1.getContractByCodeHash);
            }),
            setAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "setAddress", params, contracts_1.getContractByCodeHash);
            }),
            setCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "setCapitalisation", params, contracts_1.getContractByCodeHash);
            }),
            setExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "setExpires", params, contracts_1.getContractByCodeHash);
            }),
            delete: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "delete", params, contracts_1.getContractByCodeHash);
            }),
            getTraits: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.testMethod)(this, "getTraits", params, contracts_1.getContractByCodeHash);
            }),
        };
    }
    encodeFields(fields) {
        return (0, web3_1.encodeContractFields)((0, web3_1.addStdIdToFields)(this.contract, fields), this.contract.fieldsSig, types_1.AllStructs);
    }
    at(address) {
        return new NameInstance(address);
    }
}
// Use this object to test and deploy the contract
exports.Name = new Factory(web3_1.Contract.fromJson(Name_ral_json_1.default, "", "c87c1214c5bc7212c8c2ec57c8ea4876addee40b45c268bac30cfbd15cd79008", types_1.AllStructs));
// Use this class to interact with the blockchain
class NameInstance extends web3_1.ContractInstance {
    constructor(address) {
        super(address);
        this.view = {
            getTokenUri: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getTokenUri", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getCollectionIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getCollectionIndex", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getName: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getName", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getDescription: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getDescription", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getImage: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getImage", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getTraitCount: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getTraitCount", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getTraitAtIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getTraitAtIndex", params, contracts_1.getContractByCodeHash);
            }),
            getNFTIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getNFTIndex", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getCapitalisation", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getExpires", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            getAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getAddress", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
            setAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "setAddress", params, contracts_1.getContractByCodeHash);
            }),
            setCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "setCapitalisation", params, contracts_1.getContractByCodeHash);
            }),
            setExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "setExpires", params, contracts_1.getContractByCodeHash);
            }),
            delete: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "delete", params, contracts_1.getContractByCodeHash);
            }),
            getTraits: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.callMethod)(exports.Name, this, "getTraits", params === undefined ? {} : params, contracts_1.getContractByCodeHash);
            }),
        };
        this.transact = {
            getTokenUri: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getTokenUri", params);
            }),
            getCollectionIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getCollectionIndex", params);
            }),
            getName: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getName", params);
            }),
            getDescription: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getDescription", params);
            }),
            getImage: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getImage", params);
            }),
            getTraitCount: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getTraitCount", params);
            }),
            getTraitAtIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getTraitAtIndex", params);
            }),
            getNFTIndex: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getNFTIndex", params);
            }),
            getCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getCapitalisation", params);
            }),
            getExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getExpires", params);
            }),
            getAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getAddress", params);
            }),
            setAddress: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "setAddress", params);
            }),
            setCapitalisation: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "setCapitalisation", params);
            }),
            setExpires: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "setExpires", params);
            }),
            delete: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "delete", params);
            }),
            getTraits: (params) => __awaiter(this, void 0, void 0, function* () {
                return (0, web3_1.signExecuteMethod)(exports.Name, this, "getTraits", params);
            }),
        };
    }
    fetchState() {
        return __awaiter(this, void 0, void 0, function* () {
            return (0, web3_1.fetchContractState)(exports.Name, this);
        });
    }
    getContractEventsCurrentCount() {
        return __awaiter(this, void 0, void 0, function* () {
            return (0, web3_1.getContractEventsCurrentCount)(this.address);
        });
    }
    subscribeMetadataUpdatedEvent(options, fromCount) {
        return (0, web3_1.subscribeContractEvent)(exports.Name.contract, this, options, "MetadataUpdated", fromCount);
    }
    multicall(...callss) {
        return __awaiter(this, void 0, void 0, function* () {
            return (yield (0, web3_1.multicallMethods)(exports.Name, this, callss, contracts_1.getContractByCodeHash));
        });
    }
}
exports.NameInstance = NameInstance;
