"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SetReverseAddressName = exports.SetCapitalisation = exports.SetAddress = exports.RenewName = exports.RemoveReverseAddressName = exports.MintName = exports.MintCrop = exports.GetName = exports.GenerateToken = exports.GenerateFarm = exports.DeleteExpired = exports.DeleteCrop = void 0;
const web3_1 = require("@alephium/web3");
const contracts_1 = require("./contracts");
const DeleteCrop_ral_json_1 = __importDefault(require("../scripts/DeleteCrop.ral.json"));
const DeleteExpired_ral_json_1 = __importDefault(require("../scripts/DeleteExpired.ral.json"));
const GenerateFarm_ral_json_1 = __importDefault(require("../scripts/GenerateFarm.ral.json"));
const GenerateToken_ral_json_1 = __importDefault(require("../scripts/GenerateToken.ral.json"));
const GetName_ral_json_1 = __importDefault(require("../scripts/GetName.ral.json"));
const MintCrop_ral_json_1 = __importDefault(require("../scripts/MintCrop.ral.json"));
const MintName_ral_json_1 = __importDefault(require("../scripts/MintName.ral.json"));
const RemoveReverseAddressName_ral_json_1 = __importDefault(require("../scripts/RemoveReverseAddressName.ral.json"));
const RenewName_ral_json_1 = __importDefault(require("../scripts/RenewName.ral.json"));
const SetAddress_ral_json_1 = __importDefault(require("../scripts/SetAddress.ral.json"));
const SetCapitalisation_ral_json_1 = __importDefault(require("../scripts/SetCapitalisation.ral.json"));
const SetReverseAddressName_ral_json_1 = __importDefault(require("../scripts/SetReverseAddressName.ral.json"));
const types_1 = require("./types");
exports.DeleteCrop = new web3_1.ExecutableScript(web3_1.Script.fromJson(DeleteCrop_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.DeleteExpired = new web3_1.ExecutableScript(web3_1.Script.fromJson(DeleteExpired_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.GenerateFarm = new web3_1.ExecutableScript(web3_1.Script.fromJson(GenerateFarm_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.GenerateToken = new web3_1.ExecutableScript(web3_1.Script.fromJson(GenerateToken_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.GetName = new web3_1.ExecutableScript(web3_1.Script.fromJson(GetName_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.MintCrop = new web3_1.ExecutableScript(web3_1.Script.fromJson(MintCrop_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.MintName = new web3_1.ExecutableScript(web3_1.Script.fromJson(MintName_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.RemoveReverseAddressName = new web3_1.ExecutableScript(web3_1.Script.fromJson(RemoveReverseAddressName_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.RenewName = new web3_1.ExecutableScript(web3_1.Script.fromJson(RenewName_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.SetAddress = new web3_1.ExecutableScript(web3_1.Script.fromJson(SetAddress_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.SetCapitalisation = new web3_1.ExecutableScript(web3_1.Script.fromJson(SetCapitalisation_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
exports.SetReverseAddressName = new web3_1.ExecutableScript(web3_1.Script.fromJson(SetReverseAddressName_ral_json_1.default, "", types_1.AllStructs), contracts_1.getContractByCodeHash);
