"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.AllStructs = void 0;
const web3_1 = require("@alephium/web3");
const structs_ral_json_1 = __importDefault(require("../structs.ral.json"));
exports.AllStructs = structs_ral_json_1.default.map((json) => web3_1.Struct.fromJson(json));
